#ifndef _CPUID_H_
#define _CPUID_H_

#include <types.h>

#define CPUID_FEATURES_ECX_SSE3 BIT0
#define CPUID_FEATURES_ECX_PCLMULQDQ BIT1
#define CPUID_FEATURES_ECX_DTES64 BIT2
#define CPUID_FEATURES_ECX_MONITOR BIT3
#define CPUID_FEATURES_ECX_DS_CPL BIT4
#define CPUID_FEATURES_ECX_VMX BIT5
#define CPUID_FEATURES_ECX_SMX BIT6
#define CPUID_FEATURES_ECX_EST BIT7
#define CPUID_FEATURES_ECX_TM2 BIT8
#define CPUID_FEATURES_ECX_SSSE3 BIT9
#define CPUID_FEATURES_ECX_CNXT_ID BIT10
#define CPUID_FEATURES_ECX_FMA BIT12
#define CPUID_FEATURES_ECX_CMPXCHG16B BIT13
#define CPUID_FEATURES_ECX_XTPR BIT14
#define CPUID_FEATURES_ECX_PDCM BIT15
#define CPUID_FEATURES_ECX_PCID BIT17
#define CPUID_FEATURES_ECX_DCA BIT18
#define CPUID_FEATURES_ECX_SSE4_1 BIT19
#define CPUID_FEATURES_ECX_SSE4_2 BIT20
#define CPUID_FEATURES_ECX_X2APIC BIT21
#define CPUID_FEATURES_ECX_MOVBE BIT22
#define CPUID_FEATURES_ECX_POPCNT BIT23
#define CPUID_FEATURES_ECX_TSC_DEADLINE BIT24
#define CPUID_FEATURES_ECX_AES BIT25
#define CPUID_FEATURES_ECX_XSAVE BIT26
#define CPUID_FEATURES_ECX_OSXSAVE BIT27
#define CPUID_FEATURES_ECX_AVX BIT28
#define CPUID_FEATURES_ECX_RDRAND BIT30

#define CPUID_FEATURES_EDX_FPU BIT0
#define CPUID_FEATURES_EDX_VME BIT1
#define CPUID_FEATURES_EDX_DE BIT2
#define CPUID_FEATURES_EDX_PSE BIT3
#define CPUID_FEATURES_EDX_TSC BIT4
#define CPUID_FEATURES_EDX_MSR BIT5
#define CPUID_FEATURES_EDX_PAE BIT6
#define CPUID_FEATURES_EDX_MCE BIT7
#define CPUID_FEATURES_EDX_CX8 BIT8
#define CPUID_FEATURES_EDX_APIC BIT9
#define CPUID_FEATURES_EDX_SEP BIT11
#define CPUID_FEATURES_EDX_MTRR BIT12
#define CPUID_FEATURES_EDX_PGE BIT13
#define CPUID_FEATURES_EDX_MCA BIT14
#define CPUID_FEATURES_EDX_CMOV BIT15
#define CPUID_FEATURES_EDX_PAT BIT16
#define CPUID_FEATURES_EDX_PSE_36 BIT17
#define CPUID_FEATURES_EDX_PSN BIT18
#define CPUID_FEATURES_EDX_CLFSH BIT19
#define CPUID_FEATURES_EDX_DS BIT21
#define CPUID_FEATURES_EDX_ACPI BIT22
#define CPUID_FEATURES_EDX_MMX BIT23
#define CPUID_FEATURES_EDX_FXSR BIT24
#define CPUID_FEATURES_EDX_SSE BIT25
#define CPUID_FEATURES_EDX_SSE2 BIT26
#define CPUID_FEATURES_EDX_SS BIT27
#define CPUID_FEATURES_EDX_HTT BIT28
#define CPUID_FEATURES_EDX_TM BIT29
#define CPUID_FEATURES_EDX_PBE BIT28

static inline void cpuid(u32 eax, u32 ecx, u32 *out)
{
	asm volatile("push %rbx \n\t"
			"movq %rdx, %r8\n\t"
			"movq %rdi, %rax\n\t"
			"movq %rsi, %rcx\n\t"
			"cpuid\n\t"
			"movl %eax, 0(%r8)\n\t"
			"movl %ebx, 4(%r8)\n\t"
			"movl %ecx, 8(%r8)\n\t"
			"movl %edx, 12(%r8)\n\t"
			"pop %rbx \n\t"
		);
}

#endif

